$LOAD_PATH << '.'
require 'part.rb'
require 'db.rb'
optionsData = DB.array('maze.csv')
optionsNode = []
for i in 0...optionsData.length()
  optionsNode.push(Part.new(optionsData[i][0], optionsData[i][1], 
    optionsData[i][2], optionsData[i][3], optionsData[i][4]))
end
optionsNode[0].addNode(optionsNode[1])
optionsNode[1].addNode(optionsNode[2])
optionsNode[1].addNode(optionsNode[0])
optionsNode[1].addNode(optionsNode[3])
optionsNode[2].addNode(optionsNode[1])
optionsNode[2].addNode(optionsNode[4])
optionsNode[3].addNode(optionsNode[5])
optionsNode[3].addNode(optionsNode[1])
optionsNode[4].addNode(optionsNode[6])
optionsNode[4].addNode(optionsNode[2])
optionsNode[5].addNode(optionsNode[7])
optionsNode[5].addNode(optionsNode[3])
optionsNode[5].addNode(optionsNode[8])
optionsNode[6].addNode(optionsNode[4])
optionsNode[6].addNode(optionsNode[10])
optionsNode[6].addNode(optionsNode[9])
optionsNode[7].addNode(optionsNode[5])
optionsNode[8].addNode(optionsNode[11])
optionsNode[8].addNode(optionsNode[5])
optionsNode[8].addNode(optionsNode[13])
optionsNode[9].addNode(optionsNode[14])
optionsNode[9].addNode(optionsNode[15])
optionsNode[9].addNode(optionsNode[6])
optionsNode[10].addNode(optionsNode[6])
optionsNode[10].addNode(optionsNode[16])
optionsNode[11].addNode(optionsNode[8])
optionsNode[11].addNode(optionsNode[17])
optionsNode[11].addNode(optionsNode[12])
optionsNode[12].addNode(optionsNode[13])
optionsNode[12].addNode(optionsNode[11])
optionsNode[13].addNode(optionsNode[12])
optionsNode[13].addNode(optionsNode[8])
optionsNode[13].addNode(optionsNode[18])
optionsNode[14].addNode(optionsNode[9])
optionsNode[14].addNode(optionsNode[19])
optionsNode[15].addNode(optionsNode[9])
optionsNode[15].addNode(optionsNode[20])
optionsNode[16].addNode(optionsNode[21])
optionsNode[16].addNode(optionsNode[10])
optionsNode[17].addNode(optionsNode[11])
optionsNode[18].addNode(optionsNode[22])
optionsNode[18].addNode(optionsNode[13])
optionsNode[18].addNode(optionsNode[23])
optionsNode[19].addNode(optionsNode[14])
optionsNode[20].addNode(optionsNode[15])
optionsNode[21].addNode(optionsNode[25])
optionsNode[21].addNode(optionsNode[16])
optionsNode[21].addNode(optionsNode[24])
optionsNode[22].addNode(optionsNode[18])
optionsNode[23].addNode(optionsNode[26])
optionsNode[23].addNode(optionsNode[18])
optionsNode[24].addNode(optionsNode[27])
optionsNode[24].addNode(optionsNode[21])
optionsNode[25].addNode(optionsNode[21])
optionsNode[25].addNode(optionsNode[28])
optionsNode[26].addNode(optionsNode[23])
optionsNode[27].addNode(optionsNode[24])
optionsNode[27].addNode(optionsNode[29])
optionsNode[28].addNode(optionsNode[30])
optionsNode[28].addNode(optionsNode[25])
optionsNode[29].addNode(optionsNode[32])
optionsNode[29].addNode(optionsNode[31])
optionsNode[29].addNode(optionsNode[27])
optionsNode[30].addNode(optionsNode[28])
optionsNode[30].addNode(optionsNode[33])
optionsNode[31].addNode(optionsNode[29])
optionsNode[32].addNode(optionsNode[29])
optionsNode[33].addNode(optionsNode[34])
optionsNode[33].addNode(optionsNode[30])
optionsNode[34].addNode(optionsNode[33])
optionsNode[34].addNode(optionsNode[35])
optionsNode[35].addNode(optionsNode[36])
optionsNode[35].addNode(optionsNode[34])
optionsNode[36].addNode(optionsNode[35])
optionsNode[36].addNode(optionsNode[37])

oldPart = optionsNode[0]
newPart = optionsNode[0]
while newPart.id() != 'part37'
  newPart = oldPart.maze()
  oldPart = newPart 
  #puts oldPart.id()
end
optionsNode[37].maze()